<?php if ($detect->isMobile()) : ?>
<?php else : ?>
<?php endif; ?>
	<section id="blog">
		<header id="wrap">
			<div class="container">
            	<div class="row">
                    <span class="blg-titulo">Política de Privacidade</span>
            	</div>
            	<div class="row blg-ul">
                	<ul>
                    	<li>
                            <span class="blg-li-tag">Política de Privacidade</span>
                            <span class="blg-li-titulo">Global Telecom</span>
                            <span class="blg-li-detalhes"><?php echo $sobre_3 ?></span>
                        </li>
                    </ul>
            	</div>
			</div>
		</header>
	</section>
